// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7f9FnrZp1uFlcx7XgdBEZ_D62Ro-s_dY',
    appId: '1:894530379264:web:7bd6872b7f263f526d42e5',
    messagingSenderId: '894530379264',
    projectId: 'journey-deegre',
    authDomain: 'journey-deegre.firebaseapp.com',
    storageBucket: 'journey-deegre.firebasestorage.app',
    measurementId: 'G-T7K4P00J6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnDnNNZCa1-Gv3L7JK_0g-QJz_2bmDY_A',
    appId: '1:894530379264:android:7307bc00c3d54ed36d42e5',
    messagingSenderId: '894530379264',
    projectId: 'journey-deegre',
    storageBucket: 'journey-deegre.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMY73CvOoI3fILU1crhjysOjJckkJ6cRc',
    appId: '1:894530379264:ios:ff2378dc6898375a6d42e5',
    messagingSenderId: '894530379264',
    projectId: 'journey-deegre',
    storageBucket: 'journey-deegre.firebasestorage.app',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMY73CvOoI3fILU1crhjysOjJckkJ6cRc',
    appId: '1:894530379264:ios:ff2378dc6898375a6d42e5',
    messagingSenderId: '894530379264',
    projectId: 'journey-deegre',
    storageBucket: 'journey-deegre.firebasestorage.app',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7f9FnrZp1uFlcx7XgdBEZ_D62Ro-s_dY',
    appId: '1:894530379264:web:353b51f4629a219d6d42e5',
    messagingSenderId: '894530379264',
    projectId: 'journey-deegre',
    authDomain: 'journey-deegre.firebaseapp.com',
    storageBucket: 'journey-deegre.firebasestorage.app',
    measurementId: 'G-2LEYEHPHZN',
  );

}